// event.payload from the hook receiving a proactive trigger

const payload = {
  type: "proactive-trigger",
  payload: {
    type: "proactive-trigger",
    channel: "web",
    payload: { text: "fake message" },
    scenario: "relance",
  },
};

// event.state from the hook receiving a proactive trigger

const state = {
  __stacktrace: [],
  user: {
    timezone: 2,
    language: "en",
    webchatCustomId: {
      id: "E53023",
      firstName: "Thomas",
      token:
        "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJpc3MiOiJodHRwOlwvXC9saXZlaXQuYXBpXC91c2VyXC9hdXRoZW50aWZpY2F0aW9uIiwiaWF0IjoxNjU4OTA5NjM1LCJleHAiOjE2NTg5OTYwMzUsIm5iZiI6MTY1ODkwOTYzNSwianRpIjoiUkxGajlMcTAxa1pRRU94eSIsInN1YiI6IkU1MzAyMyIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjciLCJyb2xlcyI6InNjb3BlX2FkbWluLCBzY29wZV9hZG1pbiJ9.frjo8WCk6RyMvQse-UvYQyZteQJ1im-uYnRqvAMb-CyZu0UmPO1Y0WKVhTJHoRwsi6BMiyObDrfYYGNKpsvunJr-tdKrMU0c4usEKIHWnP23-FbyqBwOoCRDGrrcfcJXpS8Ctz8s8ZihQ26lROJU0ondQM2qc_biGFQCqpnSxZevORY8ujX0Yxd3Z_xlKMMv4BBHrg3NssNcZX1D3e12LnPjEVLUycglq2-8gLj9AG9PV1Pjn9zI0vEA2bCcrmybwVi0Cae1EieADTBoKObx0JcO2F34oPySbPSSRk6UPulV_Pu31sOk4aJ70xZe79GqXvDdrk2WA1eXGFcSruS2GBoThD__El5hc8nR6eR5lwX68f35magqrVlzb66-ZvuJZCRWEAEluYaQcJZfIED-dFTrlyIZ5PionCEggtaunrC7CLYYRgr9WjqeM3xyEyDPR030r_XCPhb4qZHVg8R0kjIqGx9XcPDEzj1t5eWx4ru6Kap-o-V6Nfy2BrmggqT4nbPpGNDcE1DAtaOLncLN2QqWzOCsr_PVTOxuHBd-AVsLUwv5jk6Sajad8vQ2Lwk52AbNncW1bXMNApENcsj9DONVO0a4HF3pSCjt1hUbbHEPTHClgGuuR3PAM0fWSSRB1i18zR9vjT940RPP7wWT7DXP_qe6p25WfysnwssKARs",
      scenario: "relance-safecheck",
    },
    firstName: "Thomas",
    id: "E53023",
    token:
      "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJpc3MiOiJodHRwOlwvXC9saXZlaXQuYXBpXC91c2VyXC9hdXRoZW50aWZpY2F0aW9uIiwiaWF0IjoxNjU4OTA5NjM1LCJleHAiOjE2NTg5OTYwMzUsIm5iZiI6MTY1ODkwOTYzNSwianRpIjoiUkxGajlMcTAxa1pRRU94eSIsInN1YiI6IkU1MzAyMyIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjciLCJyb2xlcyI6InNjb3BlX2FkbWluLCBzY29wZV9hZG1pbiJ9.frjo8WCk6RyMvQse-UvYQyZteQJ1im-uYnRqvAMb-CyZu0UmPO1Y0WKVhTJHoRwsi6BMiyObDrfYYGNKpsvunJr-tdKrMU0c4usEKIHWnP23-FbyqBwOoCRDGrrcfcJXpS8Ctz8s8ZihQ26lROJU0ondQM2qc_biGFQCqpnSxZevORY8ujX0Yxd3Z_xlKMMv4BBHrg3NssNcZX1D3e12LnPjEVLUycglq2-8gLj9AG9PV1Pjn9zI0vEA2bCcrmybwVi0Cae1EieADTBoKObx0JcO2F34oPySbPSSRk6UPulV_Pu31sOk4aJ70xZe79GqXvDdrk2WA1eXGFcSruS2GBoThD__El5hc8nR6eR5lwX68f35magqrVlzb66-ZvuJZCRWEAEluYaQcJZfIED-dFTrlyIZ5PionCEggtaunrC7CLYYRgr9WjqeM3xyEyDPR030r_XCPhb4qZHVg8R0kjIqGx9XcPDEzj1t5eWx4ru6Kap-o-V6Nfy2BrmggqT4nbPpGNDcE1DAtaOLncLN2QqWzOCsr_PVTOxuHBd-AVsLUwv5jk6Sajad8vQ2Lwk52AbNncW1bXMNApENcsj9DONVO0a4HF3pSCjt1hUbbHEPTHClgGuuR3PAM0fWSSRB1i18zR9vjT940RPP7wWT7DXP_qe6p25WfysnwssKARs",
    "": [
      {
        id_worker: "E53023",
        pass_rate: "33.33",
        rule_code: "MFA",
        current_status: "FAIL",
        last_update_time: "2022-06-30 11:00:43.007632",
        last_update_by: "E53023",
        id_event_history: 2571,
        title: "Authentication Multifacteur",
        valid_text: "Vous avez configuré l'authentication multifacteur",
        invalid_text: "Vous n'avez pas configuré l'authentication multifacteur",
        rule_type: "PHONE",
        action_text: "Pensez à configuré l'authentication multifacteur",
        status_text: "Vous n'avez pas configuré l'authentication multifacteur",
      },
      {
        id_worker: "E53023",
        pass_rate: "33.33",
        rule_code: "MAJSEC",
        current_status: "FAIL",
        last_update_time: "2022-06-30 11:00:43.007632",
        last_update_by: "E53023",
        id_event_history: 2570,
        title: "Mises-à-jour Sécurité",
        valid_text: "Votre système d'exploitation est à jour",
        invalid_text: "Votre système d'exploitation n'est pas à jour",
        rule_type: "COMPUTER",
        action_text: "Pensez à mettre à jour votre poste",
        status_text: "Votre système d'exploitation n'est pas à jour",
      },
      {
        id_worker: "E53023",
        pass_rate: "33.33",
        rule_code: "SOPHOS",
        current_status: "FAIL",
        last_update_time: "2022-06-30 11:00:43.007632",
        last_update_by: "E53023",
        id_event_history: 2569,
        title: "Désinstallation Sophos",
        valid_text: "Votre client Sophos a été désinstallé",
        invalid_text: "Votre client Sophs n'est pas d´ésinstallé",
        rule_type: "LOGICIEL",
        action_text: "Pensez à désinstaller votre VPN Sophos",
        status_text: "Votre client Sophs n'est pas d´ésinstallé",
      },
      {
        id_worker: "E53023",
        pass_rate: "33.33",
        rule_code: "INTUNE",
        current_status: "PASS",
        last_update_time: "2022-05-31 10:36:05.942607",
        last_update_by: "E53023",
        id_event_history: 83,
        title: "Paramètrage MS Intune",
        valid_text: "Votre compte est bien configuré dans Microsoft Intune",
        invalid_text:
          "Votre compte n'est pas bien configuré dans Microsoft Intune",
        rule_type: "COMPUTER",
        action_text: "Pensez à paramètrer MS Intune",
        status_text: "Votre compte est bien configuré dans Microsoft Intune",
      },
      {
        id_worker: "E53023",
        pass_rate: "33.33",
        rule_code: "EDR",
        current_status: "PASS",
        last_update_time: "2022-05-31 10:36:05.942607",
        last_update_by: "E53023",
        id_event_history: 84,
        title: "Installation MS EDR",
        valid_text:
          "Microsoft EDR est bien installé sur votre poste de travail",
        invalid_text:
          "Microsoft EDR n'est pas bien installé sur votre poste de travail",
        rule_type: "LOGICIEL",
        action_text: "Pensez à installer MS EDR",
        status_text:
          "Microsoft EDR est bien installé sur votre poste de travail",
      },
      {
        id_worker: "E53023",
        pass_rate: "33.33",
        rule_code: "BITLOCKER",
        current_status: "PASS",
        last_update_time: "2022-05-31 10:36:05.942607",
        last_update_by: "E53023",
        id_event_history: 85,
        title: "Installation Bitlocker",
        valid_text: "Votre poste est chiffré avec Bitlocker",
        invalid_text: "Votre poste n'est pas chiffré avec Bitlocker",
        rule_type: "COMPUTER",
        action_text: "Pensez à installer Bitlocker",
        status_text: "Votre poste est chiffré avec Bitlocker",
      },
      {
        id_worker: "E53023",
        pass_rate: "33.33",
        rule_code: "UAC",
        current_status: null,
        last_update_time: null,
        last_update_by: null,
        id_event_history: null,
        title: "Contrôle de Compte Utilisateur",
        valid_text:
          "Le contrôle du compte de l'utilisateur Windows (UAC) est active",
        invalid_text:
          "Le contrôle du compte de l'utilisateur  Windows (UAC) n'est pas active",
        rule_type: "COMPUTER",
        action_text: "Pensez à activer le UAC de Windows",
        status_text:
          "Le contrôle du compte de l'utilisateur  Windows (UAC) n'est pas active",
      },
      {
        id_worker: "E53023",
        pass_rate: "33.33",
        rule_code: "ADMIN",
        current_status: null,
        last_update_time: null,
        last_update_by: null,
        id_event_history: null,
        title: "Droits Admin",
        valid_text: "Votre compte a les droits d'administrateur",
        invalid_text: "Votre compte n'a pas les droits d'administrateur",
        rule_type: "COMPUTER",
        action_text: "Pensez à déclarer vos droits d'administrateur",
        status_text: "Votre compte n'a pas les droits d'administrateur",
      },
      {
        id_worker: "E53023",
        pass_rate: "33.33",
        rule_code: "LICENCE_WIN",
        current_status: null,
        last_update_time: null,
        last_update_by: null,
        id_event_history: null,
        title: "Licences Microsoft",
        valid_text: "Votre machine a une licence Windows valide et activée ",
        invalid_text:
          "Votre machine n'as pas une licence Windows valide et activée",
        rule_type: "COMPUTER",
        action_text: "Pensez à activer la licence Windows",
        status_text:
          "Votre machine n'as pas une licence Windows valide et activée",
      },
    ],
    litData: "FAIL",
    conformity: {
      id_worker: "E53023",
      pass_rate: "33.33",
      rule_code: "SOPHOS",
      current_status: "FAIL",
      last_update_time: "2022-06-30 11:00:43.007632",
      last_update_by: "E53023",
      id_event_history: 2569,
      title: "Désinstallation Sophos",
      valid_text: "Votre client Sophos a été désinstallé",
      invalid_text: "Votre client Sophs n'est pas d´ésinstallé",
      rule_type: "LOGICIEL",
      action_text: "Pensez à désinstaller votre VPN Sophos",
      status_text: "Votre client Sophs n'est pas d´ésinstallé",
    },
  },
  context: {},
  session: { lastMessages: [], workflows: {} },
  temp: {},
};
